"use client";
import type {Session,User} from "@supabase/supabase-js";
import {useRouter} from "next/navigation";
import {createContext,useCallback,useContext,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type ToastType="success"|"error"|"info";type Toast={id:number;message:string;type:ToastType};
type AuthValue={user:User|null;session:Session|null;isLoginModalOpen:boolean;openLoginModal:()=>void;closeLoginModal:()=>void;showToast:(m:string,t?:ToastType)=>void;signOut:()=>Promise<void>};
const AuthContext=createContext<AuthValue|undefined>(undefined);
export function AuthProvider({children}:{children:React.ReactNode}){const router=useRouter();const [user,setUser]=useState<User|null>(null);const [session,setSession]=useState<Session|null>(null);const [isLoginModalOpen,setIsLoginModalOpen]=useState(false);const [toast,setToast]=useState<Toast|null>(null);const showToast=useCallback((message:string,type:ToastType="info")=>setToast({id:Date.now(),message,type}),[]);const openLoginModal=useCallback(()=>setIsLoginModalOpen(true),[]);const closeLoginModal=useCallback(()=>setIsLoginModalOpen(false),[]);const signOut=useCallback(async()=>{try{await createClient().auth.signOut();setUser(null);setSession(null);showToast("已退出登录。","success");router.refresh();}catch{showToast("退出失败，请稍后再试。","error");}},[router,showToast]);useEffect(()=>{const supabase=createClient();supabase.auth.getSession().then(({data})=>{setSession(data.session);setUser(data.session?.user??null);});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setUser(next?.user??null);router.refresh();});return()=>subscription.unsubscribe();},[router]);const value=useMemo(()=>({user,session,isLoginModalOpen,openLoginModal,closeLoginModal,showToast,signOut}),[user,session,isLoginModalOpen,openLoginModal,closeLoginModal,showToast,signOut]);return <AuthContext.Provider value={value}>{children}{toast?<div className="fixed right-4 top-4 z-[120] max-w-sm rounded-xl border bg-white px-4 py-3 shadow-lg"><p className="text-sm font-semibold">{toast.type==="error"?"错误":toast.type==="success"?"成功":"提示"}</p><p className="mt-1 text-sm">{toast.message}</p><button className="absolute right-2 top-2" onClick={()=>setToast(null)}>×</button></div>:null}</AuthContext.Provider>}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useAuth must be used within AuthProvider");return ctx;}
